### ISSUE TITLE
Running `pyamiimage` from commandline and in IDEs

### ISSUE THREAD

**Issue by petermr** [petermr/pyamiimage#8]
I and others are having difficulties running `pyamiimage`. The main symptom is inability to relatively import from sibling files and directories.
I thought we had solved this problem - but we haven't. 

Unfortunately this is a multiparameter probelm.
I am using a directory structure:
```
pyamiimage/
[snipped]
│   └── 2021_11_06_InCoB_2021.pptx
├── pyamiimagex/
│   ├── __init__.py
│   ├── ami_arrow.py
│   ├── ami_edge_manager.py
│   ├── ami_graph_all.py
│   ├── ami_image.py
│   ├── ami_ocr.py
│   ├── ami_plot.py
│   ├── ami_skeleton.py
│   ├── ami_util.py
│   ├── bbox.py
│   ├── cleaner.py
│   ├── commandline.py
│   ├── contour.py
│   ├── examples.py
│   ├── examples_tesseract.py
│   ├── flood_fill.py
│   ├── image_exploration.py
│   ├── imageanal.py
│   ├── octree.py
│   ├── plot_demo.py
│   ├── svg.py
│   ├── tesseract_hocr.py
│   ├── tesseract_new.py
│   └── text_box.py
├── requirements.txt
├── setup.py
├── temp
[...]
└── test
    ├── __init__.py
    ├── alex_pico
[...]
    │   ├── pone.0054762.g004.jpg
    │   └── test1.png
    ├── biosynth_path_2.jpg
    ├── comparison_images
    │   ├── gray.png
    │   ├── inverted.png
    │   ├── original.png
    │   ├── white_binary.png
    │   └── white_skeleton.png
    ├── context.py
    ├── example_ami_ocr.py
    ├── example_tesseract.py
    ├── explore.py
    ├── generate_compare_files.py
    ├── resources
[...]
    │   ├── biosynth_path_1
    │   │   ├── biosynth_path_1.txt
    │   │   ├── biosynth_path_1_default.txt
    │   │   ├── hocr.html
    │   │   └── raw.png
    │   ├── biosynth_path_2
[...]
    │   └── test_skeleton.png
    ├── resources.py
    ├── test_ami_graph.py
    ├── test_ami_image.py
    ├── test_ami_ocr.py
    ├── test_ami_plot.py
    ├── test_ami_skeleton.py
    ├── test_ami_util.py
    ├── test_arrow.py
    ├── test_bbox.py
    ├── test_colour_sep.py
    ├── test_image_tools.py
    ├── test_svg.py
    ├── test_tesseract_hocr.py
    ├── test_text_and_arrows.py
    └── test_text_box.py
```
Note that the root of the code is called `pyamiimagex` as I think some mechanisms look for the first matching name on the path. This worked for `py4ami/pyamix` 

The imports in `pyamiimagex/ami_graph_all.py` look like:
```
# local
from ..pyamiimagex.ami_image import AmiImage
from ..pyamiimagex.ami_plot import AmiLine, X, Y
from ..pyamiimagex.ami_util import AmiUtil
from ..pyamiimagex.svg import BBox
from ..pyamiimagex.text_box import TextBox
```
and in the tests are similar

* from commandline 
```
cd ~/workspace/pyamiimage
git checkout pmr_ami_image
python -m pyamiimage.pyamiimage.commandline --help
```
gives:
```
python -m pyamiimage.pyamiimagex.commandline --help
/opt/anaconda3/bin/python: Error while finding module specification for 'pyamiimage.pyamiimagex.commandline' (ModuleNotFoundError: No module named 'pyamiimage.pyamiimagex')
```
However if I go to the directory ABOVE 
```
 cd ..
(base) pm286macbook:workspace pm286$ pwd
/Users/pm286/workspace
(base) pm286macbook:workspace pm286$ python -m pyamiimage.pyamiimagex.commandline --help
usage: commandline.py [-h] [-t] [infile] [outfile]

Welcome to pyamiimagex, view --help

positional arguments:
  infile
  outfile

optional arguments:
  -h, --help  show this help message and exit
  -t, --text  Run AmiOCR on a given Image
```
It works. This cannot be right!

So...
Please can everyone who gets something working paste to this Issue. Please give OS and environment. (I am MACOSX)

This is driving me insane. The problem is that each attempted solution requires changing a lot of moving parts all at the 
same time.

**Comment by anuvc** [comment]
Python stores a list of directories to search for modules called `sys,path`. This directories in this list is the namespace for imports in python. Whenever Python interpreter encounters an `import` statement, it searches for that package or module in the `sys.path` list **sequentially**.  The word 'sequentially' is important because it determines the precedence in the case of multiple modules or packages with the same name. Python will choose the name that it finds first in the list. 

By default python has a few entries in `sys.path`, which helps us import in-built packages and packages installed via `pip`. Whenever a python file is run, python also adds the directory of the file being run, so that you can simply import from packages and modules that are within the same directory.

While this sounds simple, this can lead to unintuitive behaviour of imports. 
Suppose you have an import statement within the module `pyamiimagex.ami_ocr` as such:
```
from ami_image import AmiImage
```
This would make sense as ami_ocr and ami_image are in the same directory, right? 
You're right this would work, assuming you run `ami_ocr.py` directly or call it from any other module in the same directory.

**BUT**

If you try to call ami_ocr as a module from a file in a different directory, say, `test/test_ami_ocr.py` And add a line such as this:
```
from pyamiimagex.ami_ocr import AmiOCR
```
The system will throw as error at the line `from ami_image import AmiImage` in `ami_ocr`. This is because when you are running `test/test_ami_ocr.py`, `pyamiimage/test` gets added to `sys.path`, but `pyamiimage/pyamiimagex` does not.

Remember that the path that is added to python path for searching for modules (stored in `sys.path`) is the file the program **first runs**. For example, if you are calling a module in `pyamiimagex` such as `from pyamiimagex.ami_ocr import AmiOCR` from your `test` directory. The directory that is added to `sys.path` is `/Users/pm286/workspace/pyamiimage/test`. You can verify this by adding a print statement somewhere such as `print(sys.path)`. 

Also, since this is lower in the directory tree, you can't import modules from `pyamiimagex` without relative imports. You have to basically 'go up' a directory to be able to see the `pyamiimagex` directory. Even then, for some reason relative imports does not seem to work if going up a directory involves going up to the root directory of the project. I don't like relative import for such inconsistencies, so I tend to avoid them. 

So how do we solve our problem without relative imports?

The solution to this problem is given in this nice article about [structuring your python project](https://docs.python-guide.org/writing/structure/#test-suite). 

The idea is, you add a new file called `context,py` in your `test` directory, whose job is to automatically add the top level of the project eg. `/Users/pm286/workspace/pyamiimage` to the *beginning* of your `sys.path`. Import context in the beginning of your test file, and then do absolute imports from the top level. Now all the directories in your top level including your package directory is visible to the running test and it's imported modules.

The `context.py` file looks like this:
```
import os
import sys

top_level = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

# add top level root directory to the beginning path
sys.path.insert(0, top_level)
```

Use absolute paths within the package modules. So inside `ami_ocr.py` write:
```
from pyamiimagex.ami_image import AmiImage
```

And within your `test_ami_ocr.py` write:
```
import context
from pyamiimagex.ami_ocr import AmiOCR # this works now
```
 
 I've solved the imports in this project and pushed them. The main points are:
- There is no need to change the name of the package directory(i.e. don't use `pyamiimagex`), this only leads to confusion when creating a python package. It's best to have the package name as the directory name for the modules. To make sure you are importing the right package/module, check your `sys.path`.
- Do NOT have `__init__.py` everywhere in your repository. Only have the file in the package directory and its sub directories. For example, having `__init__.py`  in test directory might cause problem with importing files in the same test directory(such as `resources`).
- Use absolute imports everywhere for importing modules from packages. For example, use `from pyamiimage.ami_ocr import AmiOCR` whenever you wish to import AmiOCR from ami_ocr. Do NOT use relative imports such as from `..pyamiimage.ami_ocr import AmiOCR `or from `.ami_ocr import AmiOCR`. Relative imports can sometimes be inconsistent (for example we can't use relative imports from the root directory) and will cause confusion.
- `import context` in the beginning of your file if the file you are running is not in the root directory, to make sure that the absolute imports work.

Hopefully that solves your problem!
